DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);


CREATE TABLE destinations (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  city VARCHAR(50) NOT NULL,
  airportCode VARCHAR(3) NOT NULL,
  rating INTEGER NOT NULL
);