INSERT INTO user (username, email, password)
VALUES
  ('userguy', 'userguy@gmail.com', 'password123'),
  ('userlady', 'userlady@gmail.com', 'password321'),
  ('userperson', 'userperson@gmail.com', 'password213');

INSERT INTO destination (city, airport_code)
VALUES
  ('Atlanta','ATL'),
  ('Dallas','DFW'),
  ('Denver','DEN'),
  ('Chicago','ORD'),
  ('Los Angeles','LAX'),
  ('Charlotte','CLT'),
  ('Las Vegas','LAS'),
  ('Phoenix','PHX'),
  ('Orlando','MCO'),
  ('Seattle','SEA'),
  ('Miami','MIA'),
  ('Houston','IAH'),
  ('New York City','JFK'),
  ('Fort Lauderdale','FLL'),
  ('San Francisco','SFO'),
  ('Newark','EWR'),
  ('Minneapolis','MSP'),
  ('Detriot','DTW'),
  ('Boston','BOS'),
  ('Philadelphia','PHL'),
  ('St. Louis','STL'),
  ('Baltimore','BWI'),
  ('Tampa','TPA'),
  ('San Diego','SAN'),
  ('Salt Lake City','SLC'),
  ('Washington, D.C.','IAD'),
  ('Nashville','BNA'),
  ('New York City','LGA'),
  ('Dallas','DAL'),
  ('Washington, D.C.','DCA'),
  ('Portland','PDX'),
  ('Honolulu','HNL'),
  ('Houston','HOU'),
  ('Austin','AUS'),
  ('Chicago','MDW'),
  ('Fort Myers','RSW'),
  ('Sacramento','SMF'),
  ('New Orleans','MSY'),
  ('Raleigh','RDU'),
  ('San Juan','SJU'),
  ('San Jose','SJC'),
  ('Oakland','OAK'),
  ('Kansas City','MCI'),
  ('Cleveland','CLE'),
  ('Indianapolis','IND'),
  ('San Antonio','SAT'),
  ('Orange County','SNA'),
  ('Pittsburgh','PIT'),
  ('Cincinatti','CVG'),
  ('Columbus','CMH'),
  ('Palm Beach','PBI'),
  ('Jackonsville','JAX'),
  ('Milwaukee','MKE'),
  ('Ontario','ONT'),
  ('Hartford','BDL'),
  ('Kahului','OGC'),
  ('Anchorage','ANC'),
  ('Omaha','OMA'),
  ('Memphis','MEM'),
  ('Reno','RNO');

  INSERT INTO review (rating, user.id, destination.id)
  VALUES
  (1, 1, 481);
