INSERT INTO users (username, email, password)
VALUES
  ('userguy', 'userguy@gmail.com', 'password123'),
  ('userlady', 'userlady@gmail.com', 'password321'),
  ('userperson', 'userperson@gmail.com', 'password213')

INSERT INTO destinations (city, airportCode, rating)
VALUES
  ('Atlanta','ATL', 0),
  ('Dallas', 'DFW', 0),
  ('Denver','DEN', 0),
  ('Chicago','ORD', 0),
  ('Los Angeles','LAX', 0),
  ('Charlotte','CLT', 0),
  ('Las Vegas','LAS', 0),
  ('Phoenix','PHX', 0),
  ('Orlando','MCO', 0),
  ('Seattle','SEA', 0),
  ('Miami','MIA', 0),
  ('Houston','IAH', 0),
  ('New York City','JFK', 0),
  ('Fort Lauderdale','FLL', 0),
  ('San Francisco','SFO', 0),
  ('Newark','EWR', 0),
  ('Minneapolis','MSP', 0),
  ('Detriot','DTW', 0),
  ('Boston','BOS', 0),
  ('Philadelphia','PHL', 0),
  ('St. Louis','STL', 0),
  ('Baltimore','BWI', 0),
  ('Tampa','TPA', 0),
  ('San Diego','SAN', 0),
  ('Salt Lake City','SLC', 0),
  ('Washington, D.C.','IAD', 0),
  ('Nashville','BNA', 0),
  ('New York City','LGA', 0),
  ('Dallas','DAL', 0),
  ('Washington, D.C.','DCA', 0),
  ('Portland','PDX', 0),
  ('Honolulu','HNL', 0),
  ('Houston','HOU', 0),
  ('Austin','AUS', 0),
  ('Chicago','MDW', 0),
  ('Fort Myers','RSW', 0),
  ('Sacramento','RSW', 0),
  ('New Orleans','MSY', 0),
  ('Raleigh','RDU', 0),
  ('San Juan','SJU', 0),
  ('San Jose','SJC', 0),
  ('Oakland','OAK', 0),
  ('Kansas City','MCI', 0),
  ('Cleveland','CLE', 0),
  ('Indianapolis','IND', 0),
  ('San Antonio','SAT', 0),
  ('Orange County','SNA', 0),
  ('Pittsburgh','PIT', 0),
  ('Cincinatti','CVG', 0),
  ('Columbus','CMH', 0),
  ('Palm Beach','PBI', 0),
  ('Jackonsville','JAX', 0),
  ('Milwaukee','MKE', 0),
  ('Ontario','ONT', 0),
  ('Hartford','BDL', 0),
  ('Kahului','OGC', 0),
  ('Anchorage','ANC', 0),
  ('Omaha','OMA', 0),
  ('Memphis','MEM', 0),
  ('Reno','RNO', 0)
